//
//  XCNotification.h
//  XCMonit_Ip
//
//  Created by xia zhonglin  on 14-5-22.
//  Copyright (c) 2014年 xia zhonglin . All rights reserved.
//

#ifndef XCMonit_Ip_XCNotification_h
#define XCMonit_Ip_XCNotification_h

#define NS_SCAN_DEVICE_NUMBER_VC @"NS_SCAN_DEVICE_NUMBER_VC"
#define NS_REMOTE_FILE_END_VC @"NS_REMOTE_FILE_END_VC"
#define NS_TIME_CURRENT_PAN_EVENT_VC @"NS_TIME_CURRENT_PAN_EVENT_VC"
#define NS_APPLICATION_IPC_ENTER_BACKGROUP  @"NS_APPLICATION_IPC_ENTER_BACKGROUP"
#define NSCONNECT_P2P_DVR_FAIL_VC @"NSCONNECT_P2P_DVR_FAIL_VC"
#define NSCONNECT_P2P_FAIL_VC   @"NSCONNECT_P2P_FAIL_VC"
#define NSCONNECT_P2P_DISCONNECT @"NSCONNECT_P2P_DISCONNECT"
#define NSSWITCH_P2P_FAIL_VC    @"NSSWITCH_P2P_FAIL_VC"
#define NSUPDATE_DEVICE_LIST_VC    @"NSUPDATGE_DEVICE_LIST_VC"
#define NSUPDATE_HOME_TABLEVIEW_VC   @"NSUPDATE_HOME_TABLEVIEW_VC"
#define NSKEY_BOARD_RETURN_VC   @"NSKEY_BOARD_RETURN_VC"
#define NSUPDATE_DEV_NAME_VC   @"NSUPDATE_DEV_NAME_VC"
#define NS_APPLITION_ENTER_BACK  @"NS_APPLITION_ENTER_BACK"
#define NS_APPLITION_ENTER_FOREG @"NS_APPLITION_ENTER_FOREG"
#define NS_APPLITION_BECOME_ACTIVE @"NS_APPLITION_BECOME_ACTIVE"
#define NS_DELETE_IMAGE_VC   @"NS_DELETE_IMAGE_VC"
#define NS_UPDATE_IMAGE_VC    @"NS_UPDATE_IMAGE_VC"
#define NS_GET_DEVICE_LIST_VC    @"NS_GET_DEVICE_LIST_VC"
#define NS_RTSP_DISCONNECT_VC     @"NS_RTSP_DISCONNECT_VC"
#define NS_SWITCH_TRAN_OPEN_VC    @"NS_SWITCH_TRAN_OPEN_VC"

#define NS_SEARCH_DEVICE_FOR_WLAN_VC @"NS_SEARCH_DEVICE_FOR_WLAN_VC"

#define NS_CUSTOM_BAR_TITLE_VC    @"NS_CUSTOM_BAR_TITLE_VC"

#define NS_UPDATE_PASSWROD_VC    @"NS_UPDATE_PASSWROD_VC"

#define NS_UPDATE_USER_INFO_VC @"NS_UPDATE_USER_INFO_VC"

#define NS_UPDATEPWD_EXIT_VC @"NS_UPDATEPWD_EXIT_VC"

#endif
